# Generated by Django 3.1.7 on 2021-12-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_applicant_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_registration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
