# Generated by Django 3.1.7 on 2021-12-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20211222_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_first_name', models.CharField(max_length=20)),
                ('candidate_last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
