# Generated by Django 3.1.4 on 2022-01-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_auto_20211231_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=30)),
                ('stream', models.CharField(max_length=30)),
                ('institute_name', models.CharField(max_length=30)),
                ('university_name', models.CharField(max_length=100)),
                ('passing_year', models.CharField(max_length=30)),
                ('percentage', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='address_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_address', models.CharField(max_length=250)),
                ('address_same', models.CharField(max_length=10)),
                ('permanent_address', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25)),
                ('taluka', models.CharField(max_length=25)),
                ('village', models.CharField(max_length=25)),
                ('pincode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='other_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(max_length=20)),
                ('caste', models.CharField(max_length=20)),
                ('person_with_disablity', models.CharField(max_length=20)),
            ],
        ),
    ]
