# Generated by Django 3.1.4 on 2022-02-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_academic_information_address_information_other_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_file', models.FileField(upload_to='upload/')),
                ('hsc_file', models.FileField(upload_to='upload/')),
                ('caste_file', models.FileField(upload_to='upload/')),
                ('non_creamy_layer_file', models.FileField(upload_to='upload/')),
                ('passport_photo_file', models.FileField(upload_to='upload/')),
                ('signature_file', models.FileField(upload_to='upload/')),
            ],
        ),
        migrations.AlterField(
            model_name='academic_information',
            name='passing_year',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='academic_information',
            name='percentage',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address_information',
            name='address_same',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='address_information',
            name='pincode',
            field=models.IntegerField(max_length=20),
        ),
    ]
