# Generated by Django 3.1.7 on 2021-12-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TET_Officers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_end_date',
            field=models.DateField(
                auto_now=False, auto_now_add=False, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_str_date',
            field=models.DateField(
                auto_now=False, auto_now_add=False, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_name',
            field=models.CharField(max_length=20),
        ),
    ]
