# Generated by Django 3.1.7 on 2021-12-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TET_Officers', '0003_auto_20211222_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_str_date',
            field=models.DateField(null=True),
        ),
    ]
